/*
 *  Swing Calculator
 *  Developed by Bertassi
 *  Copyright 2018 All Rights Reserved
 */
package br.com.bertassi.mvccalculator.gui;

import br.com.bertassi.mvccalculator.gui.interfaces.CalculatorInterface;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author eduardo
 */
public class NewCalculatorGUI extends javax.swing.JFrame implements CalculatorInterface
{

    /**
     * Creates new form TestGUI
     */
    public NewCalculatorGUI ()
    {
        this.initComponents();
        this.loadCalculatorScreen();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanelScreen = new javax.swing.JPanel();
        jLabelAbout = new javax.swing.JLabel();
        jLabelExpression = new javax.swing.JLabel();
        jLabelVisor = new javax.swing.JLabel();
        jPanelButtons = new javax.swing.JPanel();
        jButtonAcumulatorClear = new javax.swing.JButton();
        jButtonChangeSignal = new javax.swing.JButton();
        jButtonPercentage = new javax.swing.JButton();
        jButtonDivision = new javax.swing.JButton();
        jButtonSeven = new javax.swing.JButton();
        jButtonEight = new javax.swing.JButton();
        jButtonNine = new javax.swing.JButton();
        jButtonMultiplication = new javax.swing.JButton();
        jButtonFour = new javax.swing.JButton();
        jButtonFive = new javax.swing.JButton();
        jButtonSix = new javax.swing.JButton();
        jButtonSubtraction = new javax.swing.JButton();
        jButtonOne = new javax.swing.JButton();
        jButtonTwo = new javax.swing.JButton();
        jButtonThree = new javax.swing.JButton();
        jButtonSum = new javax.swing.JButton();
        jButtonZero = new javax.swing.JButton();
        jButtonComma = new javax.swing.JButton();
        jButtonEqual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(360, 620));

        jPanelScreen.setBackground(new java.awt.Color(26, 26, 26));

        jLabelAbout.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAbout.setText("About");
        jLabelAbout.setMaximumSize(new java.awt.Dimension(50, 30));
        jLabelAbout.setMinimumSize(new java.awt.Dimension(50, 30));
        jLabelAbout.setPreferredSize(new java.awt.Dimension(50, 30));
        jLabelAbout.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jLabelAboutMousePressed(evt);
            }
        });

        jLabelExpression.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExpression.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelExpression.setText("250 + 250 = 500");
        jLabelExpression.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelExpression.setMaximumSize(new java.awt.Dimension(300, 25));
        jLabelExpression.setMinimumSize(new java.awt.Dimension(300, 25));
        jLabelExpression.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabelVisor.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelVisor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVisor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelVisor.setText("-123456789.0");
        jLabelVisor.setMaximumSize(new java.awt.Dimension(300, 105));
        jLabelVisor.setMinimumSize(new java.awt.Dimension(300, 105));
        jLabelVisor.setPreferredSize(new java.awt.Dimension(300, 105));

        javax.swing.GroupLayout jPanelScreenLayout = new javax.swing.GroupLayout(jPanelScreen);
        jPanelScreen.setLayout(jPanelScreenLayout);
        jPanelScreenLayout.setHorizontalGroup(
            jPanelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelScreenLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelVisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelExpression, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        jPanelScreenLayout.setVerticalGroup(
            jPanelScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelScreenLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabelAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelExpression, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabelVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanelButtons.setBackground(new java.awt.Color(0, 0, 0));

        jButtonAcumulatorClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/ac.png"))); // NOI18N
        jButtonAcumulatorClear.setBorder(null);
        jButtonAcumulatorClear.setBorderPainted(false);
        jButtonAcumulatorClear.setIconTextGap(0);
        jButtonAcumulatorClear.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonAcumulatorClear.setMaximumSize(new java.awt.Dimension(100, 81));
        jButtonAcumulatorClear.setMinimumSize(new java.awt.Dimension(100, 81));
        jButtonAcumulatorClear.setPreferredSize(new java.awt.Dimension(100, 81));
        jButtonAcumulatorClear.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jButtonAcumulatorClearMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jButtonAcumulatorClearMouseReleased(evt);
            }
        });

        jButtonChangeSignal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/signal.png"))); // NOI18N
        jButtonChangeSignal.setBorder(null);
        jButtonChangeSignal.setBorderPainted(false);
        jButtonChangeSignal.setMaximumSize(new java.awt.Dimension(80, 81));
        jButtonChangeSignal.setMinimumSize(new java.awt.Dimension(80, 81));
        jButtonChangeSignal.setName(""); // NOI18N
        jButtonChangeSignal.setPreferredSize(new java.awt.Dimension(80, 81));
        jButtonChangeSignal.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jButtonChangeSignalMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jButtonChangeSignalMouseReleased(evt);
            }
        });

        jButtonPercentage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/percentage.png"))); // NOI18N
        jButtonPercentage.setBorder(null);
        jButtonPercentage.setBorderPainted(false);
        jButtonPercentage.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonPercentage.setMaximumSize(new java.awt.Dimension(80, 81));
        jButtonPercentage.setMinimumSize(new java.awt.Dimension(80, 81));
        jButtonPercentage.setPreferredSize(new java.awt.Dimension(80, 81));
        jButtonPercentage.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jButtonPercentageMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jButtonPercentageMouseReleased(evt);
            }
        });

        jButtonDivision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/division.png"))); // NOI18N
        jButtonDivision.setBorder(null);
        jButtonDivision.setBorderPainted(false);
        jButtonDivision.setPreferredSize(new java.awt.Dimension(100, 81));
        jButtonDivision.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jButtonDivisionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jButtonDivisionMouseReleased(evt);
            }
        });

        jButtonSeven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/seven.png"))); // NOI18N
        jButtonSeven.setBorder(null);
        jButtonSeven.setBorderPainted(false);
        jButtonSeven.setIconTextGap(0);
        jButtonSeven.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSeven.setMaximumSize(new java.awt.Dimension(100, 80));
        jButtonSeven.setMinimumSize(new java.awt.Dimension(100, 80));
        jButtonSeven.setPreferredSize(new java.awt.Dimension(100, 80));
        jButtonSeven.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jButtonSevenMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jButtonSevenMouseReleased(evt);
            }
        });

        jButtonEight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/eight.png"))); // NOI18N
        jButtonEight.setBorder(null);
        jButtonEight.setBorderPainted(false);
        jButtonEight.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEight.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonEight.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonEight.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonEight.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jButtonEightMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jButtonEightMouseReleased(evt);
            }
        });

        jButtonNine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/nine.png"))); // NOI18N
        jButtonNine.setBorder(null);
        jButtonNine.setBorderPainted(false);
        jButtonNine.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonNine.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonNine.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonNine.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonNine.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jButtonNineMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jButtonNineMouseReleased(evt);
            }
        });

        jButtonMultiplication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/multiplication.png"))); // NOI18N
        jButtonMultiplication.setBorder(null);
        jButtonMultiplication.setBorderPainted(false);
        jButtonMultiplication.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonMultiplication.setMaximumSize(new java.awt.Dimension(100, 80));
        jButtonMultiplication.setMinimumSize(new java.awt.Dimension(100, 80));
        jButtonMultiplication.setPreferredSize(new java.awt.Dimension(100, 80));
        jButtonMultiplication.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jButtonMultiplicationMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jButtonMultiplicationMouseReleased(evt);
            }
        });

        jButtonFour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/four.png"))); // NOI18N
        jButtonFour.setBorder(null);
        jButtonFour.setBorderPainted(false);
        jButtonFour.setIconTextGap(0);
        jButtonFour.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFour.setMaximumSize(new java.awt.Dimension(100, 80));
        jButtonFour.setMinimumSize(new java.awt.Dimension(100, 80));
        jButtonFour.setPreferredSize(new java.awt.Dimension(100, 80));
        jButtonFour.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jButtonFourMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jButtonFourMouseReleased(evt);
            }
        });

        jButtonFive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/five.png"))); // NOI18N
        jButtonFive.setBorder(null);
        jButtonFive.setBorderPainted(false);
        jButtonFive.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFive.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonFive.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonFive.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonFive.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jButtonFiveMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jButtonFiveMouseReleased(evt);
            }
        });

        jButtonSix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/six.png"))); // NOI18N
        jButtonSix.setBorder(null);
        jButtonSix.setBorderPainted(false);
        jButtonSix.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSix.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonSix.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonSix.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonSix.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jButtonSixMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jButtonSixMouseReleased(evt);
            }
        });

        jButtonSubtraction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/subtraction.png"))); // NOI18N
        jButtonSubtraction.setBorder(null);
        jButtonSubtraction.setBorderPainted(false);
        jButtonSubtraction.setMaximumSize(new java.awt.Dimension(100, 80));
        jButtonSubtraction.setMinimumSize(new java.awt.Dimension(100, 80));
        jButtonSubtraction.setPreferredSize(new java.awt.Dimension(100, 80));
        jButtonSubtraction.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jButtonSubtractionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jButtonSubtractionMouseReleased(evt);
            }
        });

        jButtonOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/one.png"))); // NOI18N
        jButtonOne.setBorder(null);
        jButtonOne.setBorderPainted(false);
        jButtonOne.setIconTextGap(0);
        jButtonOne.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonOne.setMaximumSize(new java.awt.Dimension(100, 80));
        jButtonOne.setMinimumSize(new java.awt.Dimension(100, 80));
        jButtonOne.setPreferredSize(new java.awt.Dimension(100, 80));
        jButtonOne.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jButtonOneMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jButtonOneMouseReleased(evt);
            }
        });

        jButtonTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/two.png"))); // NOI18N
        jButtonTwo.setBorder(null);
        jButtonTwo.setBorderPainted(false);
        jButtonTwo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonTwo.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonTwo.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonTwo.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonTwo.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jButtonTwoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jButtonTwoMouseReleased(evt);
            }
        });

        jButtonThree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/three.png"))); // NOI18N
        jButtonThree.setBorder(null);
        jButtonThree.setBorderPainted(false);
        jButtonThree.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonThree.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonThree.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonThree.setPreferredSize(new java.awt.Dimension(80, 80));
        jButtonThree.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jButtonThreeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jButtonThreeMouseReleased(evt);
            }
        });

        jButtonSum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/sum.png"))); // NOI18N
        jButtonSum.setBorder(null);
        jButtonSum.setBorderPainted(false);
        jButtonSum.setMaximumSize(new java.awt.Dimension(100, 80));
        jButtonSum.setMinimumSize(new java.awt.Dimension(100, 80));
        jButtonSum.setPreferredSize(new java.awt.Dimension(100, 80));
        jButtonSum.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jButtonSumMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jButtonSumMouseReleased(evt);
            }
        });

        jButtonZero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/zero.png"))); // NOI18N
        jButtonZero.setBorder(null);
        jButtonZero.setBorderPainted(false);
        jButtonZero.setIconTextGap(0);
        jButtonZero.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonZero.setMaximumSize(new java.awt.Dimension(180, 100));
        jButtonZero.setMinimumSize(new java.awt.Dimension(180, 100));
        jButtonZero.setPreferredSize(new java.awt.Dimension(100, 80));
        jButtonZero.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jButtonZeroMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jButtonZeroMouseReleased(evt);
            }
        });

        jButtonComma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/comma.png"))); // NOI18N
        jButtonComma.setBorder(null);
        jButtonComma.setBorderPainted(false);
        jButtonComma.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonComma.setMaximumSize(new java.awt.Dimension(80, 100));
        jButtonComma.setMinimumSize(new java.awt.Dimension(80, 100));
        jButtonComma.setPreferredSize(new java.awt.Dimension(80, 100));
        jButtonComma.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jButtonCommaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jButtonCommaMouseReleased(evt);
            }
        });

        jButtonEqual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/equal.png"))); // NOI18N
        jButtonEqual.setBorder(null);
        jButtonEqual.setBorderPainted(false);
        jButtonEqual.setMaximumSize(new java.awt.Dimension(180, 100));
        jButtonEqual.setMinimumSize(new java.awt.Dimension(180, 100));
        jButtonEqual.setPreferredSize(new java.awt.Dimension(100, 80));
        jButtonEqual.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jButtonEqualMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jButtonEqualMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelButtonsLayout.createSequentialGroup()
                    .addGap(180, 180, 180)
                    .addComponent(jButtonComma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelButtonsLayout.createSequentialGroup()
                    .addGap(260, 260, 260)
                    .addComponent(jButtonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelButtonsLayout.createSequentialGroup()
                    .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonFive, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonEight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonNine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelButtonsLayout.createSequentialGroup()
                    .addComponent(jButtonAcumulatorClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jButtonChangeSignal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jButtonPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSubtraction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelButtonsLayout.createSequentialGroup()
                    .addGap(260, 260, 260)
                    .addComponent(jButtonSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelButtonsLayout.createSequentialGroup()
                    .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonZero, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelButtonsLayout.createSequentialGroup()
                            .addComponent(jButtonOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jButtonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, 0)
                    .addComponent(jButtonThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAcumulatorClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonChangeSignal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSubtraction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEqual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonComma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcumulatorClearMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonAcumulatorClearMousePressed
    {//GEN-HEADEREND:event_jButtonAcumulatorClearMousePressed
        jButtonAcumulatorClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/pressed/ac.png")));
    }//GEN-LAST:event_jButtonAcumulatorClearMousePressed

    private void jButtonAcumulatorClearMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonAcumulatorClearMouseReleased
    {//GEN-HEADEREND:event_jButtonAcumulatorClearMouseReleased
        jButtonAcumulatorClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/ac.png")));
    }//GEN-LAST:event_jButtonAcumulatorClearMouseReleased

    private void jButtonChangeSignalMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonChangeSignalMousePressed
    {//GEN-HEADEREND:event_jButtonChangeSignalMousePressed
        jButtonChangeSignal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/pressed/signal.png")));
    }//GEN-LAST:event_jButtonChangeSignalMousePressed

    private void jButtonChangeSignalMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonChangeSignalMouseReleased
    {//GEN-HEADEREND:event_jButtonChangeSignalMouseReleased
        jButtonChangeSignal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/signal.png")));
    }//GEN-LAST:event_jButtonChangeSignalMouseReleased

    private void jButtonPercentageMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonPercentageMousePressed
    {//GEN-HEADEREND:event_jButtonPercentageMousePressed
        jButtonPercentage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/pressed/percentage.png")));
    }//GEN-LAST:event_jButtonPercentageMousePressed

    private void jButtonPercentageMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonPercentageMouseReleased
    {//GEN-HEADEREND:event_jButtonPercentageMouseReleased
        jButtonPercentage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/percentage.png")));
    }//GEN-LAST:event_jButtonPercentageMouseReleased

    private void jButtonDivisionMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonDivisionMousePressed
    {//GEN-HEADEREND:event_jButtonDivisionMousePressed
        jButtonDivision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/pressed/division.png")));
    }//GEN-LAST:event_jButtonDivisionMousePressed

    private void jButtonDivisionMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonDivisionMouseReleased
    {//GEN-HEADEREND:event_jButtonDivisionMouseReleased
        jButtonDivision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/division.png")));
    }//GEN-LAST:event_jButtonDivisionMouseReleased

    private void jButtonSevenMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonSevenMousePressed
    {//GEN-HEADEREND:event_jButtonSevenMousePressed
        jButtonSeven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/pressed/seven.png")));
    }//GEN-LAST:event_jButtonSevenMousePressed

    private void jButtonSevenMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonSevenMouseReleased
    {//GEN-HEADEREND:event_jButtonSevenMouseReleased
        jButtonSeven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/seven.png")));
    }//GEN-LAST:event_jButtonSevenMouseReleased

    private void jButtonEightMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonEightMousePressed
    {//GEN-HEADEREND:event_jButtonEightMousePressed
        jButtonEight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/pressed/eight.png")));
    }//GEN-LAST:event_jButtonEightMousePressed

    private void jButtonEightMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonEightMouseReleased
    {//GEN-HEADEREND:event_jButtonEightMouseReleased
        jButtonEight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/eight.png")));
    }//GEN-LAST:event_jButtonEightMouseReleased

    private void jButtonNineMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonNineMousePressed
    {//GEN-HEADEREND:event_jButtonNineMousePressed
        jButtonNine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/pressed/nine.png")));
    }//GEN-LAST:event_jButtonNineMousePressed

    private void jButtonNineMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonNineMouseReleased
    {//GEN-HEADEREND:event_jButtonNineMouseReleased
        jButtonNine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/nine.png")));
    }//GEN-LAST:event_jButtonNineMouseReleased

    private void jButtonMultiplicationMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonMultiplicationMousePressed
    {//GEN-HEADEREND:event_jButtonMultiplicationMousePressed
        jButtonMultiplication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/pressed/multiplication.png")));
    }//GEN-LAST:event_jButtonMultiplicationMousePressed

    private void jButtonMultiplicationMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonMultiplicationMouseReleased
    {//GEN-HEADEREND:event_jButtonMultiplicationMouseReleased
        jButtonMultiplication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/multiplication.png")));
    }//GEN-LAST:event_jButtonMultiplicationMouseReleased

    private void jButtonFourMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonFourMousePressed
    {//GEN-HEADEREND:event_jButtonFourMousePressed
        jButtonFour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/pressed/four.png")));
    }//GEN-LAST:event_jButtonFourMousePressed

    private void jButtonFourMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonFourMouseReleased
    {//GEN-HEADEREND:event_jButtonFourMouseReleased
        jButtonFour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/four.png")));
    }//GEN-LAST:event_jButtonFourMouseReleased

    private void jButtonFiveMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonFiveMousePressed
    {//GEN-HEADEREND:event_jButtonFiveMousePressed
        jButtonFive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/pressed/five.png")));
    }//GEN-LAST:event_jButtonFiveMousePressed

    private void jButtonFiveMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonFiveMouseReleased
    {//GEN-HEADEREND:event_jButtonFiveMouseReleased
        jButtonFive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/five.png")));
    }//GEN-LAST:event_jButtonFiveMouseReleased

    private void jButtonSixMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonSixMousePressed
    {//GEN-HEADEREND:event_jButtonSixMousePressed
        jButtonSix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/pressed/six.png")));
    }//GEN-LAST:event_jButtonSixMousePressed

    private void jButtonSixMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonSixMouseReleased
    {//GEN-HEADEREND:event_jButtonSixMouseReleased
        jButtonSix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/six.png")));
    }//GEN-LAST:event_jButtonSixMouseReleased

    private void jButtonSubtractionMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonSubtractionMousePressed
    {//GEN-HEADEREND:event_jButtonSubtractionMousePressed
        jButtonSubtraction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/pressed/subtraction.png")));
    }//GEN-LAST:event_jButtonSubtractionMousePressed

    private void jButtonSubtractionMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonSubtractionMouseReleased
    {//GEN-HEADEREND:event_jButtonSubtractionMouseReleased
        jButtonSubtraction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/subtraction.png")));
    }//GEN-LAST:event_jButtonSubtractionMouseReleased

    private void jButtonOneMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonOneMousePressed
    {//GEN-HEADEREND:event_jButtonOneMousePressed
        jButtonOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/pressed/one.png")));
    }//GEN-LAST:event_jButtonOneMousePressed

    private void jButtonOneMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonOneMouseReleased
    {//GEN-HEADEREND:event_jButtonOneMouseReleased
        jButtonOne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/one.png")));
    }//GEN-LAST:event_jButtonOneMouseReleased

    private void jButtonTwoMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonTwoMousePressed
    {//GEN-HEADEREND:event_jButtonTwoMousePressed
        jButtonTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/pressed/two.png")));
    }//GEN-LAST:event_jButtonTwoMousePressed

    private void jButtonTwoMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonTwoMouseReleased
    {//GEN-HEADEREND:event_jButtonTwoMouseReleased
        jButtonTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/two.png")));
    }//GEN-LAST:event_jButtonTwoMouseReleased

    private void jButtonThreeMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonThreeMousePressed
    {//GEN-HEADEREND:event_jButtonThreeMousePressed
        jButtonThree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/pressed/three.png")));
    }//GEN-LAST:event_jButtonThreeMousePressed

    private void jButtonThreeMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonThreeMouseReleased
    {//GEN-HEADEREND:event_jButtonThreeMouseReleased
        jButtonThree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/three.png")));
    }//GEN-LAST:event_jButtonThreeMouseReleased

    private void jButtonSumMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonSumMousePressed
    {//GEN-HEADEREND:event_jButtonSumMousePressed
        jButtonSum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/pressed/sum.png")));
    }//GEN-LAST:event_jButtonSumMousePressed

    private void jButtonSumMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonSumMouseReleased
    {//GEN-HEADEREND:event_jButtonSumMouseReleased
        jButtonSum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/sum.png")));
    }//GEN-LAST:event_jButtonSumMouseReleased

    private void jButtonZeroMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonZeroMousePressed
    {//GEN-HEADEREND:event_jButtonZeroMousePressed
        jButtonZero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/pressed/zero.png")));
    }//GEN-LAST:event_jButtonZeroMousePressed

    private void jButtonZeroMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonZeroMouseReleased
    {//GEN-HEADEREND:event_jButtonZeroMouseReleased
        jButtonZero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/zero.png")));
    }//GEN-LAST:event_jButtonZeroMouseReleased

    private void jButtonCommaMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonCommaMousePressed
    {//GEN-HEADEREND:event_jButtonCommaMousePressed
        jButtonComma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/pressed/comma.png")));
    }//GEN-LAST:event_jButtonCommaMousePressed

    private void jButtonCommaMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonCommaMouseReleased
    {//GEN-HEADEREND:event_jButtonCommaMouseReleased
        jButtonComma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/comma.png")));
    }//GEN-LAST:event_jButtonCommaMouseReleased

    private void jButtonEqualMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonEqualMousePressed
    {//GEN-HEADEREND:event_jButtonEqualMousePressed
        jButtonEqual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/pressed/equal.png")));
    }//GEN-LAST:event_jButtonEqualMousePressed

    private void jButtonEqualMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButtonEqualMouseReleased
    {//GEN-HEADEREND:event_jButtonEqualMouseReleased
        jButtonEqual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/equal.png")));
    }//GEN-LAST:event_jButtonEqualMouseReleased

    private void jLabelAboutMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabelAboutMousePressed
    {//GEN-HEADEREND:event_jLabelAboutMousePressed
        // O fundo fica completamente branco
        //UIManager.getDefaults().put("OptionPane.background",new Color(255,255,255));
        //UIManager.put ("Panel.background", new Color(255,255,255));
        
        JOptionPane.showOptionDialog(this, new AboutGUI(),null, JOptionPane.DEFAULT_OPTION,JOptionPane.PLAIN_MESSAGE, null, new Object[]{}, null);
    }//GEN-LAST:event_jLabelAboutMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main (String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(NewCalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run ()
            {
                new NewCalculatorGUI().setVisible(true);
            }
        });
    }

    @Override
    public JButton getJButtonAcumulatorClear ()
    {
        return jButtonAcumulatorClear;
    }

    @Override
    public void setJButtonAcumulatorClear (JButton jButtonAcumulatorClear)
    {
        this.jButtonAcumulatorClear = jButtonAcumulatorClear;
    }

    @Override
    public JButton getJButtonChangeSignal ()
    {
        return jButtonChangeSignal;
    }

    @Override
    public void setJButtonChangeSignal (JButton jButtonChangeSignal)
    {
        this.jButtonChangeSignal = jButtonChangeSignal;
    }

    @Override
    public JButton getJButtonComma ()
    {
        return jButtonComma;
    }

    @Override
    public void setJButtonComma (JButton jButtonComma)
    {
        this.jButtonComma = jButtonComma;
    }

    @Override
    public JButton getJButtonDivision ()
    {
        return jButtonDivision;
    }

    @Override
    public void setJButtonDivision (JButton jButtonDivision)
    {
        this.jButtonDivision = jButtonDivision;
    }

    @Override
    public JButton getJButtonEight ()
    {
        return jButtonEight;
    }

    @Override
    public void setJButtonEight (JButton jButtonEight)
    {
        this.jButtonEight = jButtonEight;
    }

    @Override
    public JButton getJButtonEqual ()
    {
        return jButtonEqual;
    }

    @Override
    public void setJButtonEqual (JButton jButtonEqual)
    {
        this.jButtonEqual = jButtonEqual;
    }

    @Override
    public JButton getJButtonFive ()
    {
        return jButtonFive;
    }

    @Override
    public void setJButtonFive (JButton jButtonFive)
    {
        this.jButtonFive = jButtonFive;
    }

    @Override
    public JButton getJButtonFour ()
    {
        return jButtonFour;
    }

    @Override
    public void setJButtonFour (JButton jButtonFour)
    {
        this.jButtonFour = jButtonFour;
    }

    @Override
    public JButton getJButtonMultiplication ()
    {
        return jButtonMultiplication;
    }

    @Override
    public void setJButtonMultiplication (JButton jButtonMultiplication)
    {
        this.jButtonMultiplication = jButtonMultiplication;
    }

    @Override
    public JButton getJButtonNine ()
    {
        return jButtonNine;
    }

    @Override
    public void setJButtonNine (JButton jButtonNine)
    {
        this.jButtonNine = jButtonNine;
    }

    @Override
    public JButton getJButtonOne ()
    {
        return jButtonOne;
    }

    @Override
    public void setJButtonOne (JButton jButtonOne)
    {
        this.jButtonOne = jButtonOne;
    }

    @Override
    public JButton getJButtonPercentage ()
    {
        return jButtonPercentage;
    }

    @Override
    public void setJButtonPercentage (JButton jButtonPercentage)
    {
        this.jButtonPercentage = jButtonPercentage;
    }

    @Override
    public JButton getJButtonSeven ()
    {
        return jButtonSeven;
    }

    @Override
    public void setJButtonSeven (JButton jButtonSeven)
    {
        this.jButtonSeven = jButtonSeven;
    }

    @Override
    public JButton getJButtonSix ()
    {
        return jButtonSix;
    }

    @Override
    public void setJButtonSix (JButton jButtonSix)
    {
        this.jButtonSix = jButtonSix;
    }

    @Override
    public JButton getJButtonSubtraction ()
    {
        return jButtonSubtraction;
    }

    @Override
    public void setJButtonSubtraction (JButton jButtonSubtraction)
    {
        this.jButtonSubtraction = jButtonSubtraction;
    }

    @Override
    public JButton getJButtonSum ()
    {
        return jButtonSum;
    }

    @Override
    public void setJButtonSum (JButton jButtonSum)
    {
        this.jButtonSum = jButtonSum;
    }

    @Override
    public JButton getJButtonThree ()
    {
        return jButtonThree;
    }

    @Override
    public void setJButtonThree (JButton jButtonThree)
    {
        this.jButtonThree = jButtonThree;
    }

    @Override
    public JButton getJButtonTwo ()
    {
        return jButtonTwo;
    }

    @Override
    public void setJButtonTwo (JButton jButtonTwo)
    {
        this.jButtonTwo = jButtonTwo;
    }

    @Override
    public JButton getJButtonZero ()
    {
        return jButtonZero;
    }

    @Override
    public void setJButtonZero (JButton jButtonZero)
    {
        this.jButtonZero = jButtonZero;
    }

    @Override
    public JLabel getJLabelAbout ()
    {
        return jLabelAbout;
    }

    @Override
    public void setJLabelAbout (String texto)
    {
        this.jLabelAbout.setText(texto);
    }

    @Override
    public JLabel getJLabelExpression ()
    {
        return jLabelExpression;
    }

    @Override
    public void setJLabelExpression (String texto)
    {
        this.jLabelExpression.setText(texto);
    }

    @Override
    public JLabel getJLabelVisor ()
    {
        return jLabelVisor;
    }

    @Override
    public void setJLabelVisor (String texto)
    {
        this.jLabelVisor.setText(texto);
    }

    @Override
    public JPanel getjPanelButtons ()
    {
        return jPanelButtons;
    }

    @Override
    public void setjPanelButtons (JPanel jPanelButtons)
    {
        this.jPanelButtons = jPanelButtons;
    }

    @Override
    public JPanel getjPanelScreen ()
    {
        return jPanelScreen;
    }

    @Override
    public void setjPanelScreen (JPanel jPanelScreen)
    {
        this.jPanelScreen = jPanelScreen;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcumulatorClear;
    private javax.swing.JButton jButtonChangeSignal;
    private javax.swing.JButton jButtonComma;
    private javax.swing.JButton jButtonDivision;
    private javax.swing.JButton jButtonEight;
    private javax.swing.JButton jButtonEqual;
    private javax.swing.JButton jButtonFive;
    private javax.swing.JButton jButtonFour;
    private javax.swing.JButton jButtonMultiplication;
    private javax.swing.JButton jButtonNine;
    private javax.swing.JButton jButtonOne;
    private javax.swing.JButton jButtonPercentage;
    private javax.swing.JButton jButtonSeven;
    private javax.swing.JButton jButtonSix;
    private javax.swing.JButton jButtonSubtraction;
    private javax.swing.JButton jButtonSum;
    private javax.swing.JButton jButtonThree;
    private javax.swing.JButton jButtonTwo;
    private javax.swing.JButton jButtonZero;
    private javax.swing.JLabel jLabelAbout;
    private javax.swing.JLabel jLabelExpression;
    private javax.swing.JLabel jLabelVisor;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelScreen;
    // End of variables declaration//GEN-END:variables

    /**
     * Classe interna para definir uma imagem de fundo para um painel.
     */
    private class ImagePanel extends JPanel
    {

        private final Image img;

        /**
         * Construtor da classe ImagePanel.
         */
        public ImagePanel ()
        {
            ImageIcon imageicon = new ImageIcon(getClass().getResource("/br/com/bertassi/mvccalculator/gui/resources/normal/screen.png"));
            this.img = imageicon.getImage();

            //Dimension size = new Dimension(imageicon.getIconWidth(), imageicon.getIconHeight());
            Dimension size = new Dimension(this.img.getWidth(null), this.img.getHeight(null));

            this.setPreferredSize(size);
            this.setMinimumSize(size);
            this.setMaximumSize(size);
            this.setSize(size);
            this.setLayout(null);
        }

        /**
         * É necessário sobrecarregar esse método do componente JPanel para que
         * a imagem seja carregada corretamente.
         *
         * @param g
         */
        @Override
        public void paintComponent (Graphics g)
        {
            g.drawImage(this.img, 0, 0, null);
        }
    }

    private void loadCalculatorScreen()    
    {
        this.jPanelScreen.add(new ImagePanel());
        this.setJLabelExpression("");
    }
}