/*
 * Swing Calculator
 * Developed by Bertassi
 * Copyright 2018 All Rights Reserved
 */
package br.com.bertassi.mvccalculator.gui;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author eduardo
 */
public class OldCalculatorGUI extends JFrame
{
    private String imagePath;
    
    /**
     * Creates new form CalculatorGUI
     */
    public OldCalculatorGUI ()
    {
        this.setImagePath();
        this.initComponents();
        this.setVisible(true);        
    }
    
    private void setImagePath()
    {
        this.imagePath = ("../gui/resources/images/icon.png");
    }
    
    private String getImagePath()
    {
        return this.imagePath;
    }   
    
    public JButton getJButtonAcumulatorClear ()
    {
        return jButtonAcumulatorClear;
    }

    public JButton getJButtonChangeSignal ()
    {
        return jButtonChangeSignal;
    }
    
    public JButton getJButtonPercentage ()
    {
        return jButtonPercentage;
    }
    
    public JButton getJButtonDivide ()
    {
        return jButtonDivide;
    }    
    
    public JButton getJButtonAdd ()
    {
        return jButtonAdd;
    }

    public JButton getJButtonDot ()
    {
        return jButtonDot;
    }

    public JButton getJButtonEight ()
    {
        return jButtonEight;
    }

    public JButton getJButtonEqual ()
    {
        return jButtonEqual;
    }

    public JButton getJButtonFive ()
    {
        return jButtonFive;
    }

    public JButton getJButtonFour ()
    {
        return jButtonFour;
    }

    public JButton getJButtonMultiply ()
    {
        return jButtonMultiply;
    }

    public JButton getJButtonNine ()
    {
        return jButtonNine;
    }

    public JButton getJButtonOne ()
    {
        return jButtonOne;
    }


    public JButton getJButtonSeven ()
    {
        return jButtonSeven;
    }

    public JButton getJButtonSix ()
    {
        return jButtonSix;
    }

    public JButton getJButtonSubtract ()
    {
        return jButtonSubtract;
    }

    public JButton getJButtonThree ()
    {
        return jButtonThree;
    }

    public JButton getJButtonTwo ()
    {
        return jButtonTwo;
    }

    public JButton getJButtonZero ()
    {
        return jButtonZero;
    }

    public JTextField getJTextFieldScreen ()
    {
        return jTextFieldScreen;
    }
    
    public void setJTextFieldScreen (String s)
    {
        this.jTextFieldScreen.setText(s);
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldScreen = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonAcumulatorClear = new javax.swing.JButton();
        jButtonChangeSignal = new javax.swing.JButton();
        jButtonPercentage = new javax.swing.JButton();
        jButtonDivide = new javax.swing.JButton();
        jButtonSeven = new javax.swing.JButton();
        jButtonEight = new javax.swing.JButton();
        jButtonNine = new javax.swing.JButton();
        jButtonMultiply = new javax.swing.JButton();
        jButtonFour = new javax.swing.JButton();
        jButtonFive = new javax.swing.JButton();
        jButtonSix = new javax.swing.JButton();
        jButtonSubtract = new javax.swing.JButton();
        jButtonOne = new javax.swing.JButton();
        jButtonTwo = new javax.swing.JButton();
        jButtonThree = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonZero = new javax.swing.JButton();
        jButtonDot = new javax.swing.JButton();
        jButtonEqual = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBackground(new java.awt.Color(255, 255, 0));
        setIconImage(new ImageIcon(getClass().getResource(getImagePath())).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(320, 168));
        jPanel1.setMinimumSize(new java.awt.Dimension(320, 168));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(320, 168));

        jTextFieldScreen.setEditable(false);
        jTextFieldScreen.setBackground(new java.awt.Color(26, 26, 26));
        jTextFieldScreen.setFont(new java.awt.Font("Arial", 2, 30)); // NOI18N
        jTextFieldScreen.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldScreen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldScreen.setText("123456789,0");
        jTextFieldScreen.setToolTipText("");
        jTextFieldScreen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldScreen.setMargin(new java.awt.Insets(0, 0, 0, -100));
        jTextFieldScreen.setPreferredSize(new java.awt.Dimension(320, 170));
        jTextFieldScreen.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextFieldScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setMaximumSize(new java.awt.Dimension(320, 400));
        jPanel2.setMinimumSize(new java.awt.Dimension(320, 400));
        jPanel2.setPreferredSize(new java.awt.Dimension(320, 400));
        jPanel2.setRequestFocusEnabled(false);

        jButtonAcumulatorClear.setBackground(new java.awt.Color(170, 170, 170));
        jButtonAcumulatorClear.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButtonAcumulatorClear.setText("AC");
        jButtonAcumulatorClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonAcumulatorClear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAcumulatorClear.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonAcumulatorClear.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonAcumulatorClear.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonChangeSignal.setBackground(new java.awt.Color(170, 170, 170));
        jButtonChangeSignal.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButtonChangeSignal.setText("+/-");
        jButtonChangeSignal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonChangeSignal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonChangeSignal.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonChangeSignal.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonChangeSignal.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonPercentage.setBackground(new java.awt.Color(170, 170, 170));
        jButtonPercentage.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButtonPercentage.setText("%");
        jButtonPercentage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonPercentage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPercentage.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonPercentage.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonPercentage.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonDivide.setBackground(new java.awt.Color(255, 134, 0));
        jButtonDivide.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButtonDivide.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDivide.setText("/");
        jButtonDivide.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonDivide.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDivide.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonDivide.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonDivide.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonDivide.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonSeven.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSeven.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButtonSeven.setText("7");
        jButtonSeven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonSeven.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSeven.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonSeven.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonSeven.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonEight.setBackground(new java.awt.Color(204, 204, 204));
        jButtonEight.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButtonEight.setText("8");
        jButtonEight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonEight.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEight.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonEight.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonEight.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonNine.setBackground(new java.awt.Color(204, 204, 204));
        jButtonNine.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButtonNine.setText("9");
        jButtonNine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonNine.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNine.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonNine.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonNine.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonMultiply.setBackground(new java.awt.Color(255, 134, 0));
        jButtonMultiply.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButtonMultiply.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMultiply.setText("x");
        jButtonMultiply.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonMultiply.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMultiply.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonMultiply.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonMultiply.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonFour.setBackground(new java.awt.Color(204, 204, 204));
        jButtonFour.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButtonFour.setText("4");
        jButtonFour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonFour.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFour.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonFour.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonFour.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonFive.setBackground(new java.awt.Color(204, 204, 204));
        jButtonFive.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButtonFive.setText("5");
        jButtonFive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonFive.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFive.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonFive.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonFive.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonSix.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSix.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButtonSix.setText("6");
        jButtonSix.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonSix.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSix.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonSix.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonSix.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonSubtract.setBackground(new java.awt.Color(255, 134, 0));
        jButtonSubtract.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButtonSubtract.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSubtract.setText("-");
        jButtonSubtract.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonSubtract.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSubtract.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonSubtract.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonSubtract.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonOne.setBackground(new java.awt.Color(204, 204, 204));
        jButtonOne.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButtonOne.setText("1");
        jButtonOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonOne.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonOne.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonOne.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonOne.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonTwo.setBackground(new java.awt.Color(204, 204, 204));
        jButtonTwo.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButtonTwo.setText("2");
        jButtonTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonTwo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTwo.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonTwo.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonTwo.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonThree.setBackground(new java.awt.Color(204, 204, 204));
        jButtonThree.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButtonThree.setText("3");
        jButtonThree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonThree.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonThree.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonThree.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonThree.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonAdd.setBackground(new java.awt.Color(255, 134, 0));
        jButtonAdd.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd.setText("+");
        jButtonAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAdd.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonAdd.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonAdd.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonZero.setBackground(new java.awt.Color(204, 204, 204));
        jButtonZero.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButtonZero.setText("0");
        jButtonZero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonZero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonZero.setMaximumSize(new java.awt.Dimension(160, 80));
        jButtonZero.setMinimumSize(new java.awt.Dimension(160, 80));

        jButtonDot.setBackground(new java.awt.Color(204, 204, 204));
        jButtonDot.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButtonDot.setText(",");
        jButtonDot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonDot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDot.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonDot.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonDot.setPreferredSize(new java.awt.Dimension(80, 80));

        jButtonEqual.setBackground(new java.awt.Color(255, 134, 0));
        jButtonEqual.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jButtonEqual.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEqual.setText("=");
        jButtonEqual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonEqual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEqual.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonEqual.setMinimumSize(new java.awt.Dimension(80, 80));
        jButtonEqual.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jButtonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jButtonEight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jButtonAcumulatorClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jButtonChangeSignal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonFive, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButtonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonNine, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonZero, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonFour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonSix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonThree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonChangeSignal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAcumulatorClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSeven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFive, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonTwo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonZero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jMenuBar.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar.setBorder(null);
        jMenuBar.setBorderPainted(false);
        jMenuBar.setMaximumSize(new java.awt.Dimension(35, 32767));
        jMenuBar.setMinimumSize(new java.awt.Dimension(35, 25));
        jMenuBar.setPreferredSize(new java.awt.Dimension(35, 25));

        jMenuHelp.setBackground(new java.awt.Color(0, 0, 0));
        jMenuHelp.setBorder(null);
        jMenuHelp.setForeground(new java.awt.Color(255, 255, 255));
        jMenuHelp.setMnemonic('H');
        jMenuHelp.setText("Help");
        jMenuHelp.setMinimumSize(new java.awt.Dimension(33, 20));

        jMenuItemAbout.setBackground(new java.awt.Color(0, 0, 0));
        jMenuItemAbout.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItemAbout.setMnemonic('A');
        jMenuItemAbout.setText("About");
        jMenuItemAbout.setBorder(null);
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar.add(jMenuHelp);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemAboutActionPerformed
    {//GEN-HEADEREND:event_jMenuItemAboutActionPerformed
        // O fundo fica completamente branco
        UIManager.getDefaults().put("OptionPane.background",new Color(255,255,255));
        UIManager.put ("Panel.background", new Color(255,255,255));
        
        JOptionPane.showMessageDialog(this,new AboutGUI(),null,JOptionPane.PLAIN_MESSAGE);         
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcumulatorClear;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonChangeSignal;
    private javax.swing.JButton jButtonDivide;
    private javax.swing.JButton jButtonDot;
    private javax.swing.JButton jButtonEight;
    private javax.swing.JButton jButtonEqual;
    private javax.swing.JButton jButtonFive;
    private javax.swing.JButton jButtonFour;
    private javax.swing.JButton jButtonMultiply;
    private javax.swing.JButton jButtonNine;
    private javax.swing.JButton jButtonOne;
    private javax.swing.JButton jButtonPercentage;
    private javax.swing.JButton jButtonSeven;
    private javax.swing.JButton jButtonSix;
    private javax.swing.JButton jButtonSubtract;
    private javax.swing.JButton jButtonThree;
    private javax.swing.JButton jButtonTwo;
    private javax.swing.JButton jButtonZero;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldScreen;
    // End of variables declaration//GEN-END:variables

    public static void main (String args[])
    {
        OldCalculatorGUI calculatorView = new OldCalculatorGUI();
    }  
}
